---
title: "BMI Final Project"
author: "Saila Chen"
date: "December 7, 2017"
output: html_document
---
```{r}
library(tidyverse)
library(janitor)
library(readxl)
library(stringr)
library(HH)
library("leaps")
```

interest variables: patientid, visitid,losdays2, admitedtm, is30dayreadmit, mews, evisit, icu_flag, ageyear, gender, insurancetype. 

source:https://link.springer.com/article/10.1007%2Fs00134-001-1132-2?LI=true

```{r}
gh_data=read_excel("GHProject_Dataset.xlsx") %>% 
  clean_names() %>% 
  dplyr::select(-bmi) %>% 
  na.omit() %>% 
  filter(icu_flag==0) %>% 
  mutate(los_log=log(losdays2))
gh_clean=gh_data[!duplicated(gh_data$patientid),]
```

```{r}
par(mfrow=c(1,2))
hist(gh_clean$losdays2)
hist(log(gh_clean$losdays2))

par(mfrow=c(3,3))
hist(gh_clean$evisit)
hist(gh_clean$ageyear)
hist(gh_clean$bpsystolic)
hist(gh_clean$o2sat)
hist(gh_clean$temperature)
hist(gh_clean$heartrate)
hist(gh_clean$ageyear)
hist(gh_clean$respirationrate)
hist(gh_clean$bpdiastolic)

par(mfrow=c(2,2))
hist(gh_clean$mews)
hist(gh_clean$is30dayreadmit)
hist(gh_clean$cindex)
#hist(gh_clean$gender)
#hist(gh_clean$race)
```

```{r}
par(mfrow=c(3,4))
plot(gh_clean$mews,gh_clean$los_log)
plot(gh_clean$cindex,gh_clean$los_log)
plot(gh_clean$evisit,gh_clean$los_log)
plot(gh_clean$ageyear,gh_clean$los_log)
plot(gh_clean$bpsystolic,gh_clean$los_log)
plot(gh_clean$o2sat,gh_clean$los_log)
plot(gh_clean$temperature,gh_clean$los_log)
plot(gh_clean$heartrate,gh_clean$los_log)
plot(gh_clean$ageyear,gh_clean$los_log)
plot(gh_clean$respirationrate,gh_clean$los_log)
plot(gh_clean$bpdiastolic,gh_clean$los_log)
```

```{r}
fit1=lm(los_log~is30dayreadmit+mews+cindex+evisit+ageyear+gender+insurancetype+race+religion+bpsystolic+o2sat+temperature+heartrate+respirationrate+bpdiastolic,data=gh_clean)
summary(fit1)
```

```{r}
summary(lm(los_log ~ is30dayreadmit + mews + cindex + evisit + ageyear + 
    gender + insurancetype + bpsystolic + temperature + heartrate + 
    respirationrate + bpdiastolic,data=gh_clean))

```

```{r}
best <- function(model, ...) 
{
  subsets <- regsubsets(formula(model), model.frame(model), ...)
  subsets <- with(summary(subsets),
                  cbind(p = as.numeric(rownames(which)), which, rss, rsq, adjr2, cp, bic))
  
  return(subsets)
}  
round(best(fit1, nbest = 2), 4)
```


```{r}
step(fit1, direction='backward')
```

